### ISSUE TITLE
'STM32_Pin_Info* PIN_MAP' previously declared here

### ISSUE THREAD

**Issue by SadE54** [enablersg/fram-lib#1]
Veryfing code using this library in Particle Build fails with this error:
```
FRAM/FRAM.cpp:30:18: error: 'STM32_Pin_Info* PIN_MAP' previously declared here
  STM32_Pin_Info* PIN_MAP = HAL_Pin_Map()

**Comment by kennethlimcp** [comment]
@SadE54 could you update the FRAM library and try again? @pkourany has kindly fixed it and i have released it as `v1.0.0` :)

Closing this!
